### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#25]
(Edit this comment to add additional checklist items or mark any as complete)

### Code
* [x] Export `sigma` generic 
* [x] Negative binomial log-likelihood function
* [x] Sparse matrix stuff
* [x] Enable `stan_glmer` for bernoulli, binomial, count
* [x] Enable horseshoe priors for bernoulli, binomial, count
* [x] Check if any other functions still need tests
* [x] Make tests run in less wall time by appending numbers to the test_* filenames and estimating a few outside of a `test(){}` block so that their results can be used by subsequent unit tests
* [x] Work around build issues with 32bit Windows
* [x] Selecting parameters by regex for plots
* [x] Simpler `adapt_delta` control to modeling functions (if no user-specified adapt_delta, the default depends on the prior on the regression coefficients)
* [x] `stan_glm.nb`, `stan_glmer.nb` wrappers
* [x] Tests for `ppcheck`
* [x] Tests for `plot.stanreg`
* [x] Tests for `posterior_predict`
* [x] Tests for `predict.stanreg`
* [x] Tests for `stan_polr`
* [x] Make sure documentation and functions reflect inclusion of ADVI
* [x] Decide what to do about `sigma`
* [ ] Implement ppchecking stuff from  Andrew & Sam Cook's paper
* [ ] Finish `stan_gamm4` implementation (replace guts of gam with estimates from stanfit)

### Documentation
* [x] Roxygen templates for function args
* [x] Add a help page for the plotting functions 
* [x] Remove mentions of advi from doc
* [x] Add references to BDA3 and other sources

### Vignettes
* [x] package overview
* [x] lm
* [x] aov
* [x] polr
* [x] binomial/bernoulli glm
* [x] count glm (poisson, neg-binomial) 
* [x] continuous glm (gaussian, gamma, inverse-gaussian) 
* [ ] glmer (point to the bernoulli and count vignettes and the lme4 vignettes, and discuss prior on covariance matrices) and gamm4
* [x] Check size of vignettes (should be fine now with svglite)

### Demos
* [ ] stan_glmer stuff from the second half of the ARM book

**Comment by jgabry** [comment]
@bgoodri Thoughts on what to do about `sigma`? Right now it masks (or gets masked by) `lme4::sigma`. It looks like lme4 is still exporting the `sigma` generic conditional on R < 3.3.0.

**Comment by bgoodri** [comment]
Doesn't it provide the same functionality? If so, the I can live with the
mask message. Otherwise, can we conditionally export it?

**Comment by jgabry** [comment]
When the masking happens it actually prevents it from finding the
sigma.stanreg method. Try this:

     library(rstanarm)
     library(lme4)
     sigma(example_model)

I haven't seen a way to do conditional exports using roxygen, so if we want
to do that we would probably have to just manually edit the namespace file
or do it with a script I guess.

**Comment by bgoodri** [comment]
I can live with that for now. But is the reverse true: Does loading
rstanarm mess up someone doing lme4?

**Comment by jgabry** [comment]
Yeah unfortunately it goes both ways. Both get messed up by loading the
other package.

**Comment by bgoodri** [comment]
I don't know how to deal with that. Maybe just put something in the
documentation for sigma. I guess a user could get around it with a ::.

**Comment by jgabry** [comment]
I'll add a note to the stanreg-methods doc page. Once sigma is included in
stats we can remove it.

**Comment by bgoodri** [comment]
OK. After that do you have anything else to push?

**Comment by jgabry** [comment]
Let me double check. I'll get back you in a min.

**Comment by jgabry** [comment]
Just one small fix to stanreg. I'll push in a sec.

**Comment by bgoodri** [comment]
Was that it?

**Comment by jgabry** [comment]
Ready

**Comment by jgabry** [comment]
Travis is running for the recent commits, but assuming they pass that's all I have for the moment.

**Comment by jgabry** [comment]
Do you want to leave the stan_gamm4 stuff for the next release?

**Comment by bgoodri** [comment]
stan_gamm4() is in but it will error with a "not supported yet" message if
you try to do posterior_predict() with anything other than the old data and
the old group-level stuff. We can do it for real by building off
predict.gam() in the next release.

**Comment by jgabry** [comment]
Ok that's fine. Is that a separate issue from this FIXME comment 

    # FIXME: replace guts of gam with point estimates from stanfit

you have in stan_gamm4.R?

**Comment by jgabry** [comment]
Build with my final commits is passing on travis, by the way.

**Comment by jgabry** [comment]
Should I have the loo and waic stanreg methods throw an error if the
response variables aren't identical? loo throws an error if there aren't
the same number of observations, but with rstanarm we also know if the y
values are actually the same. This can also be for next release if you want
to stick with the package as is and submit.

**Comment by bgoodri** [comment]
It is already uploaded but if it gets rejected, we can add these checks.

**Comment by jgabry** [comment]
Ok

**Comment by bgoodri** [comment]
On Fri, Jan 8, 2016 at 12:32 PM, Jonah Gabry <notifications@github.com>
wrote:

> I'll add a note to the stanreg-methods doc page. Once sigma is included in
> stats we can remove it.


Can we add a line to the end of the cleanup[.win] script to manipulate the
NAMESPACE file conditional on the version of R to handle the sigma generic?

**Comment by jgabry** [comment]
That would be good, although I've never tried something like that with the
NAMESPACE before. Probably worth giving it a try.
